# -*- coding: utf-8 -*-
"""Dataset 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RHW4qsQ1uMWHhJ6IF1clBMYZ0_brywfo
"""

import pandas as pd
import numpy as np
import streamlit as st


import pickle

file_patch1 = 'svm_classifier_saved'
with open(file_path1, 'rb') as file1:
   svm_classifier_loaded = pickle.load(file1) 

file_path2 = 'naive_bayes_saved'
with open(file_path2, 'rb') as file2:
naive_bayes_loaded = pickle.load(file2)


def main():
    st.title("Simple Streamlit Application")
    user_input = st.text_area("Enter your text here:", "")


    if st.button("Submit"):
      
        result1 = svm_classifier_loaded(user_input)
        result2 = naive_bayes_loaded(user_input)
       
        st.text("Output svm classifier:")
        st.write(result1)
        st.text("Output naive bayes:")
        st.write(result2)

if __name__ == "__main__":
    main()
