# -*- coding: utf-8 -*-
"""Dataset 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RHW4qsQ1uMWHhJ6IF1clBMYZ0_brywfo
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
import string
import nltk
from nltk import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
from nltk.corpus import stopwords
nltk.download('vader_lexicon')
nltk.download('stopwords')
nltk.download('omw-1.4')
nltk.download('punkt')
import warnings
import streamlit as st

warnings.filterwarnings('ignore')

import pickle

vectorizer_loaded = pickle.load('/content/vectorizer_saved', 'rb')

svm_classifier_loaded = pickle.load('/content/svm_classifier_saved', 'rb')

naive_bayes_loaded = pickle.load('/content/naive_bayes_saved', 'rb')

random_forest_classifier_loaded = pickle.load('/content/random_forest_classifier_saved', 'rb')

st.title("Fake Review Detector")xxxxxxxxxxxxxxxxxxxx
user_review_input = st.text_area()
st.write(user_review_input)